### ISSUE TITLE
Cannot release new version of the package. CI is stuck

### ISSUE THREAD

**Issue by vavsab** [pulumiverse/pulumi-astra#17]
Build fails. GH Action generates changes in git. They are different from local PC.
https://github.com/pulumiverse/pulumi-astra/runs/7524235454?check_suite_focus=true

**Comment by ringods** [comment]
@vavsab the main reason for this "worktree is not clean" is that you are running a different Go version than on CI. It seems the code generation is slightly different between Go versions, leading to this difference.

**Comment by vavsab** [comment]
@ringods the problem was in the missing plugins here
https://github.com/pulumiverse/pulumi-astra/blob/19feeabe8e17dd60928f428780b0c9b6964468c3/Makefile#L110
After several months of thinking I finally switched to devcontainers locally and reproduced the issue.
