### ISSUE TITLE
links 404ing on install+config page

### ISSUE THREAD

**Issue by susanev** [pulumiverse/pulumi-astra#2]
hello!

the go and python links are 404ing here
https://github.com/pulumiverse/pulumi-astra/blob/main/docs/installation-configuration.md

do yall have updated links for these? if not, would it make sense to remove them for now?

thank you for considering!

**Comment by ringods** [comment]
@susanev we are aware. At the moment, we can't publish yet to the Pypi registry as I'm trying to get access to the [`pulumiverse`](https://pypi.org/user/pulumiverse/) Pypi user account. Working with @stack72 and @joeduffy on this.

Once we get the publishing in place, these links will be correct.

**Comment by susanev** [comment]
okay, sounds good.
we will ignore the 404 notifications on these for the time being.

**Comment by ringods** [comment]
@vavsab the credentials for the different package repositories is configured. You should be able to create a release including Python and Nuget packages.

**Comment by vavsab** [comment]
@ringods npm is working
https://www.npmjs.com/package/@pulumiverse/pulumi-astra
Please review the pr to enable the rest

**Comment by vavsab** [comment]
Build is failing. Some creds issue when installing pulumictl. Will investigate it when have some free time

**Comment by vavsab** [comment]
@ringods have you changed GITHUB_TOKEN? Looks like it has no access to read this repo and its tags

**Comment by vavsab** [comment]
I see now. My gh token has expired but I have no access to set it. @ringods what do you usually use for gh token? Should send you my personal token to set the secret? 
In my company we usually use gh apps. They give much more granular control over permissions. However, it takes more effort to set it up.

**Comment by ringods** [comment]
@vavsab I have set a new value for `RELEASE_GITHUB_TOKEN`.

Switching over to GH apps is indeed better but will be done later.

**Comment by vavsab** [comment]
Looks green now. @susanev could you plz try to install again? Unfortunately, I have no access to my PC to do it...

**Comment by susanev** [comment]
all good, thx everyone!!

**Comment by vavsab** [comment]
@susanev are you sure? I still see 404 🤔
