### ISSUE TITLE
Rename npm package to `@pulumiverse/astra`

### ISSUE THREAD

**Issue by ringods** [pulumiverse/pulumi-astra#4]
With a pulumi provider repository named `organization/pulumi-myprovider`, the corresponding NPM package is usually named `@organization/myprovider` rather than `@organization/pulumi-myprovider`. 

Can you for consistency with all core Pulumi providers rename the NPM package to `@pulumiverse/astra`?

**Comment by vavsab** [comment]
> With a pulumi provider repository named `organization/pulumi-myprovider`, the corresponding NPM package is usually named `@organization/myprovider` rather than `@organization/pulumi-myprovider`.
> 
> Can you for consistency with all core Pulumi providers rename the NPM package to `@pulumiverse/astra`?

Need to reach my pc for this change. I'm on paternity leave for the next 30 days. Will try to do it someday when I have free 30 min 😄

**Comment by ringods** [comment]
No need to rush, but preferrably before you cut a new release. ;-)
